(* generated by dune *)

(** @canonical Toyc_lib.Ast *)
module Ast = Toyc_lib__Ast

(** @canonical Toyc_lib.Codegen *)
module Codegen = Toyc_lib__Codegen

(** @canonical Toyc_lib.Lexer *)
module Lexer = Toyc_lib__Lexer

(** @canonical Toyc_lib.Parser *)
module Parser = Toyc_lib__Parser

(** @canonical Toyc_lib.Semantic *)
module Semantic = Toyc_lib__Semantic
